/**
 * Country names/flags adapted from react-native-country-select 0.3.8.
 * Only territories supported by the phone metadata are included.
 * ISC License
 *
 * Copyright 2025-present Willian Barbosa Lima do Nascimento
 *
 * Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 *
 * Calling codes verified against libphonenumber-js 1.12.29 (mobile app dependency).
 * (The MIT License)
 *
 * Copyright (c) 2016 @catamphetamine <purecatamphetamine@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
export const contactCountries = [
  {
    code: 'VI',
    name: 'ABD Virjin Adaları',
    englishName: 'United States Virgin Islands',
    flag: '🇻🇮',
    callingCode: '+1',
  },
  {
    code: 'AF',
    name: 'Afganistan',
    englishName: 'Afghanistan',
    flag: '🇦🇫',
    callingCode: '+93',
  },
  {
    code: 'DE',
    name: 'Almanya',
    englishName: 'Germany',
    flag: '🇩🇪',
    callingCode: '+49',
  },
  {
    code: 'US',
    name: 'Amerika Birleşik Devletleri',
    englishName: 'United States',
    flag: '🇺🇸',
    callingCode: '+1',
  },
  {
    code: 'AS',
    name: 'Amerikan Samoası',
    englishName: 'American Samoa',
    flag: '🇦🇸',
    callingCode: '+1',
  },
  {
    code: 'AD',
    name: 'Andorra',
    englishName: 'Andorra',
    flag: '🇦🇩',
    callingCode: '+376',
  },
  {
    code: 'AO',
    name: 'Angola',
    englishName: 'Angola',
    flag: '🇦🇴',
    callingCode: '+244',
  },
  {
    code: 'AI',
    name: 'Anguilla',
    englishName: 'Anguilla',
    flag: '🇦🇮',
    callingCode: '+1',
  },
  {
    code: 'AG',
    name: 'Antigua ve Barbuda',
    englishName: 'Antigua and Barbuda',
    flag: '🇦🇬',
    callingCode: '+1',
  },
  {
    code: 'AR',
    name: 'Arjantin',
    englishName: 'Argentina',
    flag: '🇦🇷',
    callingCode: '+54',
  },
  {
    code: 'AL',
    name: 'Arnavutluk',
    englishName: 'Albania',
    flag: '🇦🇱',
    callingCode: '+355',
  },
  {
    code: 'AW',
    name: 'Aruba',
    englishName: 'Aruba',
    flag: '🇦🇼',
    callingCode: '+297',
  },
  {
    code: 'AU',
    name: 'Avustralya',
    englishName: 'Australia',
    flag: '🇦🇺',
    callingCode: '+61',
  },
  {
    code: 'AT',
    name: 'Avusturya',
    englishName: 'Austria',
    flag: '🇦🇹',
    callingCode: '+43',
  },
  {
    code: 'AZ',
    name: 'Azerbaycan',
    englishName: 'Azerbaijan',
    flag: '🇦🇿',
    callingCode: '+994',
  },
  {
    code: 'BS',
    name: 'Bahamalar',
    englishName: 'Bahamas',
    flag: '🇧🇸',
    callingCode: '+1',
  },
  {
    code: 'BH',
    name: 'Bahreyn',
    englishName: 'Bahrain',
    flag: '🇧🇭',
    callingCode: '+973',
  },
  {
    code: 'BD',
    name: 'Bangladeş',
    englishName: 'Bangladesh',
    flag: '🇧🇩',
    callingCode: '+880',
  },
  {
    code: 'BB',
    name: 'Barbados',
    englishName: 'Barbados',
    flag: '🇧🇧',
    callingCode: '+1',
  },
  {
    code: 'WS',
    name: 'Bağımsız Samoa Devleti',
    englishName: 'Samoa',
    flag: '🇼🇸',
    callingCode: '+685',
  },
  {
    code: 'BY',
    name: 'Belarus',
    englishName: 'Belarus',
    flag: '🇧🇾',
    callingCode: '+375',
  },
  {
    code: 'BZ',
    name: 'Belize',
    englishName: 'Belize',
    flag: '🇧🇿',
    callingCode: '+501',
  },
  {
    code: 'BE',
    name: 'Belçika',
    englishName: 'Belgium',
    flag: '🇧🇪',
    callingCode: '+32',
  },
  {
    code: 'BJ',
    name: 'Benin',
    englishName: 'Benin',
    flag: '🇧🇯',
    callingCode: '+229',
  },
  {
    code: 'BM',
    name: 'Bermuda',
    englishName: 'Bermuda',
    flag: '🇧🇲',
    callingCode: '+1',
  },
  {
    code: 'AE',
    name: 'Birleşik Arap Emirlikleri',
    englishName: 'United Arab Emirates',
    flag: '🇦🇪',
    callingCode: '+971',
  },
  {
    code: 'GB',
    name: 'Birleşik Krallık',
    englishName: 'United Kingdom',
    flag: '🇬🇧',
    callingCode: '+44',
  },
  {
    code: 'BO',
    name: 'Bolivya',
    englishName: 'Bolivia',
    flag: '🇧🇴',
    callingCode: '+591',
  },
  {
    code: 'BA',
    name: 'Bosna-Hersek',
    englishName: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    callingCode: '+387',
  },
  {
    code: 'BW',
    name: 'Botsvana',
    englishName: 'Botswana',
    flag: '🇧🇼',
    callingCode: '+267',
  },
  {
    code: 'BR',
    name: 'Brezilya',
    englishName: 'Brazil',
    flag: '🇧🇷',
    callingCode: '+55',
  },
  {
    code: 'IO',
    name: 'Britanya Hint Okyanusu Toprakları',
    englishName: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    callingCode: '+246',
  },
  {
    code: 'BN',
    name: 'Brunei',
    englishName: 'Brunei',
    flag: '🇧🇳',
    callingCode: '+673',
  },
  {
    code: 'BG',
    name: 'Bulgaristan',
    englishName: 'Bulgaria',
    flag: '🇧🇬',
    callingCode: '+359',
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    englishName: 'Burkina Faso',
    flag: '🇧🇫',
    callingCode: '+226',
  },
  {
    code: 'BI',
    name: 'Burundi',
    englishName: 'Burundi',
    flag: '🇧🇮',
    callingCode: '+257',
  },
  {
    code: 'BT',
    name: 'Butan',
    englishName: 'Bhutan',
    flag: '🇧🇹',
    callingCode: '+975',
  },
  {
    code: 'KY',
    name: 'Cayman Adaları',
    englishName: 'Cayman Islands',
    flag: '🇰🇾',
    callingCode: '+1',
  },
  {
    code: 'GI',
    name: 'Cebelitarık',
    englishName: 'Gibraltar',
    flag: '🇬🇮',
    callingCode: '+350',
  },
  {
    code: 'DZ',
    name: 'Cezayir',
    englishName: 'Algeria',
    flag: '🇩🇿',
    callingCode: '+213',
  },
  {
    code: 'CX',
    name: 'Christmas Adası',
    englishName: 'Christmas Island',
    flag: '🇨🇽',
    callingCode: '+61',
  },
  {
    code: 'DJ',
    name: 'Cibuti',
    englishName: 'Djibouti',
    flag: '🇩🇯',
    callingCode: '+253',
  },
  {
    code: 'CC',
    name: 'Cocos (Keeling) Adaları',
    englishName: 'Cocos (Keeling) Islands',
    flag: '🇨🇨',
    callingCode: '+61',
  },
  {
    code: 'CK',
    name: 'Cook Adaları',
    englishName: 'Cook Islands',
    flag: '🇨🇰',
    callingCode: '+682',
  },
  {
    code: 'CW',
    name: 'Curaçao',
    englishName: 'Curaçao',
    flag: '🇨🇼',
    callingCode: '+599',
  },
  {
    code: 'DK',
    name: 'Danimarka',
    englishName: 'Denmark',
    flag: '🇩🇰',
    callingCode: '+45',
  },
  {
    code: 'DO',
    name: 'Dominik Cumhuriyeti',
    englishName: 'Dominican Republic',
    flag: '🇩🇴',
    callingCode: '+1',
  },
  {
    code: 'DM',
    name: 'Dominika',
    englishName: 'Dominica',
    flag: '🇩🇲',
    callingCode: '+1',
  },
  {
    code: 'TL',
    name: 'Doğu Timor',
    englishName: 'Timor-Leste',
    flag: '🇹🇱',
    callingCode: '+670',
  },
  {
    code: 'EC',
    name: 'Ekvador',
    englishName: 'Ecuador',
    flag: '🇪🇨',
    callingCode: '+593',
  },
  {
    code: 'GQ',
    name: 'Ekvator Ginesi',
    englishName: 'Equatorial Guinea',
    flag: '🇬🇶',
    callingCode: '+240',
  },
  {
    code: 'SV',
    name: 'El Salvador',
    englishName: 'El Salvador',
    flag: '🇸🇻',
    callingCode: '+503',
  },
  {
    code: 'ID',
    name: 'Endonezya',
    englishName: 'Indonesia',
    flag: '🇮🇩',
    callingCode: '+62',
  },
  {
    code: 'ER',
    name: 'Eritre',
    englishName: 'Eritrea',
    flag: '🇪🇷',
    callingCode: '+291',
  },
  {
    code: 'AM',
    name: 'Ermenistan',
    englishName: 'Armenia',
    flag: '🇦🇲',
    callingCode: '+374',
  },
  {
    code: 'EE',
    name: 'Estonya',
    englishName: 'Estonia',
    flag: '🇪🇪',
    callingCode: '+372',
  },
  {
    code: 'SZ',
    name: 'Esvatini',
    englishName: 'Eswatini',
    flag: '🇸🇿',
    callingCode: '+268',
  },
  {
    code: 'ET',
    name: 'Etiyopya',
    englishName: 'Ethiopia',
    flag: '🇪🇹',
    callingCode: '+251',
  },
  {
    code: 'FK',
    name: 'Falkland (Malvina) Adaları',
    englishName: 'Falkland Islands',
    flag: '🇫🇰',
    callingCode: '+500',
  },
  {
    code: 'FO',
    name: 'Faroe Adaları',
    englishName: 'Faroe Islands',
    flag: '🇫🇴',
    callingCode: '+298',
  },
  {
    code: 'MA',
    name: 'Fas',
    englishName: 'Morocco',
    flag: '🇲🇦',
    callingCode: '+212',
  },
  {
    code: 'FJ',
    name: 'Fiji',
    englishName: 'Fiji',
    flag: '🇫🇯',
    callingCode: '+679',
  },
  {
    code: 'CI',
    name: 'Fildişi Sahili',
    englishName: 'Ivory Coast',
    flag: '🇨🇮',
    callingCode: '+225',
  },
  {
    code: 'PH',
    name: 'Filipinler',
    englishName: 'Philippines',
    flag: '🇵🇭',
    callingCode: '+63',
  },
  {
    code: 'PS',
    name: 'Filistin',
    englishName: 'Palestine',
    flag: '🇵🇸',
    callingCode: '+970',
  },
  {
    code: 'FI',
    name: 'Finlandiya',
    englishName: 'Finland',
    flag: '🇫🇮',
    callingCode: '+358',
  },
  {
    code: 'FR',
    name: 'Fransa',
    englishName: 'France',
    flag: '🇫🇷',
    callingCode: '+33',
  },
  {
    code: 'GF',
    name: 'Fransız Guyanası',
    englishName: 'French Guiana',
    flag: '🇬🇫',
    callingCode: '+594',
  },
  {
    code: 'PF',
    name: 'Fransız Polinezyası',
    englishName: 'French Polynesia',
    flag: '🇵🇫',
    callingCode: '+689',
  },
  {
    code: 'GA',
    name: 'Gabon',
    englishName: 'Gabon',
    flag: '🇬🇦',
    callingCode: '+241',
  },
  {
    code: 'GM',
    name: 'Gambiya',
    englishName: 'Gambia',
    flag: '🇬🇲',
    callingCode: '+220',
  },
  {
    code: 'GH',
    name: 'Gana',
    englishName: 'Ghana',
    flag: '🇬🇭',
    callingCode: '+233',
  },
  {
    code: 'GN',
    name: 'Gine',
    englishName: 'Guinea',
    flag: '🇬🇳',
    callingCode: '+224',
  },
  {
    code: 'GW',
    name: 'Gine-Bissau',
    englishName: 'Guinea-Bissau',
    flag: '🇬🇼',
    callingCode: '+245',
  },
  {
    code: 'GD',
    name: 'Grenada',
    englishName: 'Grenada',
    flag: '🇬🇩',
    callingCode: '+1',
  },
  {
    code: 'GL',
    name: 'Grönland',
    englishName: 'Greenland',
    flag: '🇬🇱',
    callingCode: '+299',
  },
  {
    code: 'GP',
    name: 'Guadeloupe',
    englishName: 'Guadeloupe',
    flag: '🇬🇵',
    callingCode: '+590',
  },
  {
    code: 'GU',
    name: 'Guam',
    englishName: 'Guam',
    flag: '🇬🇺',
    callingCode: '+1',
  },
  {
    code: 'GT',
    name: 'Guatemala',
    englishName: 'Guatemala',
    flag: '🇬🇹',
    callingCode: '+502',
  },
  {
    code: 'GG',
    name: 'Guernsey',
    englishName: 'Guernsey',
    flag: '🇬🇬',
    callingCode: '+44',
  },
  {
    code: 'GY',
    name: 'Guyana',
    englishName: 'Guyana',
    flag: '🇬🇾',
    callingCode: '+592',
  },
  {
    code: 'ZA',
    name: 'Güney Afrika',
    englishName: 'South Africa',
    flag: '🇿🇦',
    callingCode: '+27',
  },
  {
    code: 'KR',
    name: 'Güney Kore',
    englishName: 'South Korea',
    flag: '🇰🇷',
    callingCode: '+82',
  },
  {
    code: 'SS',
    name: 'Güney Sudan',
    englishName: 'South Sudan',
    flag: '🇸🇸',
    callingCode: '+211',
  },
  {
    code: 'GE',
    name: 'Gürcistan',
    englishName: 'Georgia',
    flag: '🇬🇪',
    callingCode: '+995',
  },
  {
    code: 'HT',
    name: 'Haiti',
    englishName: 'Haiti',
    flag: '🇭🇹',
    callingCode: '+509',
  },
  {
    code: 'IN',
    name: 'Hindistan',
    englishName: 'India',
    flag: '🇮🇳',
    callingCode: '+91',
  },
  {
    code: 'NL',
    name: 'Hollanda',
    englishName: 'Netherlands',
    flag: '🇳🇱',
    callingCode: '+31',
  },
  {
    code: 'HN',
    name: 'Honduras',
    englishName: 'Honduras',
    flag: '🇭🇳',
    callingCode: '+504',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    englishName: 'Hong Kong',
    flag: '🇭🇰',
    callingCode: '+852',
  },
  {
    code: 'HR',
    name: 'Hırvatistan',
    englishName: 'Croatia',
    flag: '🇭🇷',
    callingCode: '+385',
  },
  {
    code: 'IQ',
    name: 'Irak',
    englishName: 'Iraq',
    flag: '🇮🇶',
    callingCode: '+964',
  },
  {
    code: 'JM',
    name: 'Jamaika',
    englishName: 'Jamaica',
    flag: '🇯🇲',
    callingCode: '+1',
  },
  {
    code: 'JP',
    name: 'Japonya',
    englishName: 'Japan',
    flag: '🇯🇵',
    callingCode: '+81',
  },
  {
    code: 'JE',
    name: 'Jersey',
    englishName: 'Jersey',
    flag: '🇯🇪',
    callingCode: '+44',
  },
  {
    code: 'KH',
    name: 'Kamboçya',
    englishName: 'Cambodia',
    flag: '🇰🇭',
    callingCode: '+855',
  },
  {
    code: 'CM',
    name: 'Kamerun',
    englishName: 'Cameroon',
    flag: '🇨🇲',
    callingCode: '+237',
  },
  {
    code: 'CA',
    name: 'Kanada',
    englishName: 'Canada',
    flag: '🇨🇦',
    callingCode: '+1',
  },
  {
    code: 'ME',
    name: 'Karadağ',
    englishName: 'Montenegro',
    flag: '🇲🇪',
    callingCode: '+382',
  },
  {
    code: 'BQ',
    name: 'Karayip Hollandası',
    englishName: 'Caribbean Netherlands',
    flag: '',
    callingCode: '+599',
  },
  {
    code: 'QA',
    name: 'Katar',
    englishName: 'Qatar',
    flag: '🇶🇦',
    callingCode: '+974',
  },
  {
    code: 'KZ',
    name: 'Kazakistan',
    englishName: 'Kazakhstan',
    flag: '🇰🇿',
    callingCode: '+7',
  },
  {
    code: 'KE',
    name: 'Kenya',
    englishName: 'Kenya',
    flag: '🇰🇪',
    callingCode: '+254',
  },
  {
    code: 'KI',
    name: 'Kiribati',
    englishName: 'Kiribati',
    flag: '🇰🇮',
    callingCode: '+686',
  },
  {
    code: 'CO',
    name: 'Kolombiya',
    englishName: 'Colombia',
    flag: '🇨🇴',
    callingCode: '+57',
  },
  {
    code: 'KM',
    name: 'Komorlar',
    englishName: 'Comoros',
    flag: '🇰🇲',
    callingCode: '+269',
  },
  {
    code: 'CG',
    name: 'Kongo Cumhuriyeti',
    englishName: 'Congo',
    flag: '🇨🇬',
    callingCode: '+242',
  },
  {
    code: 'CD',
    name: 'Kongo Demokratik Cumhuriyeti',
    englishName: 'DR Congo',
    flag: '🇨🇩',
    callingCode: '+243',
  },
  {
    code: 'XK',
    name: 'Kosova',
    englishName: 'Kosovo',
    flag: '🇽🇰',
    callingCode: '+383',
  },
  {
    code: 'CR',
    name: 'Kosta Rika',
    englishName: 'Costa Rica',
    flag: '🇨🇷',
    callingCode: '+506',
  },
  {
    code: 'KW',
    name: 'Kuveyt',
    englishName: 'Kuwait',
    flag: '🇰🇼',
    callingCode: '+965',
  },
  {
    code: 'KP',
    name: 'Kuzey Kore',
    englishName: 'North Korea',
    flag: '🇰🇵',
    callingCode: '+850',
  },
  {
    code: 'MK',
    name: 'Kuzey Makedonya',
    englishName: 'North Macedonia',
    flag: '🇲🇰',
    callingCode: '+389',
  },
  {
    code: 'MP',
    name: 'Kuzey Mariana Adaları',
    englishName: 'Northern Mariana Islands',
    flag: '🇲🇵',
    callingCode: '+1',
  },
  {
    code: 'CU',
    name: 'Küba',
    englishName: 'Cuba',
    flag: '🇨🇺',
    callingCode: '+53',
  },
  {
    code: 'CY',
    name: 'Kıbrıs',
    englishName: 'Cyprus',
    flag: '🇨🇾',
    callingCode: '+357',
  },
  {
    code: 'KG',
    name: 'Kırgızistan',
    englishName: 'Kyrgyzstan',
    flag: '🇰🇬',
    callingCode: '+996',
  },
  {
    code: 'LA',
    name: 'Laos',
    englishName: 'Laos',
    flag: '🇱🇦',
    callingCode: '+856',
  },
  {
    code: 'LS',
    name: 'Lesotho',
    englishName: 'Lesotho',
    flag: '🇱🇸',
    callingCode: '+266',
  },
  {
    code: 'LV',
    name: 'Letonya',
    englishName: 'Latvia',
    flag: '🇱🇻',
    callingCode: '+371',
  },
  {
    code: 'LR',
    name: 'Liberya',
    englishName: 'Liberia',
    flag: '🇱🇷',
    callingCode: '+231',
  },
  {
    code: 'LY',
    name: 'Libya',
    englishName: 'Libya',
    flag: '🇱🇾',
    callingCode: '+218',
  },
  {
    code: 'LI',
    name: 'Lihtenştayn',
    englishName: 'Liechtenstein',
    flag: '🇱🇮',
    callingCode: '+423',
  },
  {
    code: 'LT',
    name: 'Litvanya',
    englishName: 'Lithuania',
    flag: '🇱🇹',
    callingCode: '+370',
  },
  {
    code: 'LB',
    name: 'Lübnan',
    englishName: 'Lebanon',
    flag: '🇱🇧',
    callingCode: '+961',
  },
  {
    code: 'LU',
    name: 'Lüksemburg',
    englishName: 'Luxembourg',
    flag: '🇱🇺',
    callingCode: '+352',
  },
  {
    code: 'HU',
    name: 'Macaristan',
    englishName: 'Hungary',
    flag: '🇭🇺',
    callingCode: '+36',
  },
  {
    code: 'MG',
    name: 'Madagaskar',
    englishName: 'Madagascar',
    flag: '🇲🇬',
    callingCode: '+261',
  },
  {
    code: 'MO',
    name: 'Makao',
    englishName: 'Macau',
    flag: '🇲🇴',
    callingCode: '+853',
  },
  {
    code: 'MW',
    name: 'Malavi',
    englishName: 'Malawi',
    flag: '🇲🇼',
    callingCode: '+265',
  },
  {
    code: 'MV',
    name: 'Maldivler',
    englishName: 'Maldives',
    flag: '🇲🇻',
    callingCode: '+960',
  },
  {
    code: 'MY',
    name: 'Malezya',
    englishName: 'Malaysia',
    flag: '🇲🇾',
    callingCode: '+60',
  },
  {
    code: 'ML',
    name: 'Mali',
    englishName: 'Mali',
    flag: '🇲🇱',
    callingCode: '+223',
  },
  {
    code: 'MT',
    name: 'Malta',
    englishName: 'Malta',
    flag: '🇲🇹',
    callingCode: '+356',
  },
  {
    code: 'IM',
    name: 'Man Adası',
    englishName: 'Isle of Man',
    flag: '🇮🇲',
    callingCode: '+44',
  },
  {
    code: 'MH',
    name: 'Marshall Adaları',
    englishName: 'Marshall Islands',
    flag: '🇲🇭',
    callingCode: '+692',
  },
  {
    code: 'MQ',
    name: 'Martinik',
    englishName: 'Martinique',
    flag: '🇲🇶',
    callingCode: '+596',
  },
  {
    code: 'MU',
    name: 'Mauritius',
    englishName: 'Mauritius',
    flag: '🇲🇺',
    callingCode: '+230',
  },
  {
    code: 'YT',
    name: 'Mayotte',
    englishName: 'Mayotte',
    flag: '🇾🇹',
    callingCode: '+262',
  },
  {
    code: 'MX',
    name: 'Meksika',
    englishName: 'Mexico',
    flag: '🇲🇽',
    callingCode: '+52',
  },
  {
    code: 'FM',
    name: 'Mikronezya',
    englishName: 'Micronesia',
    flag: '🇫🇲',
    callingCode: '+691',
  },
  {
    code: 'MD',
    name: 'Moldova',
    englishName: 'Moldova',
    flag: '🇲🇩',
    callingCode: '+373',
  },
  {
    code: 'MC',
    name: 'Monako',
    englishName: 'Monaco',
    flag: '🇲🇨',
    callingCode: '+377',
  },
  {
    code: 'MS',
    name: 'Montserrat',
    englishName: 'Montserrat',
    flag: '🇲🇸',
    callingCode: '+1',
  },
  {
    code: 'MR',
    name: 'Moritanya',
    englishName: 'Mauritania',
    flag: '🇲🇷',
    callingCode: '+222',
  },
  {
    code: 'MZ',
    name: 'Mozambik',
    englishName: 'Mozambique',
    flag: '🇲🇿',
    callingCode: '+258',
  },
  {
    code: 'MN',
    name: 'Moğolistan',
    englishName: 'Mongolia',
    flag: '🇲🇳',
    callingCode: '+976',
  },
  {
    code: 'MM',
    name: 'Myanmar',
    englishName: 'Myanmar',
    flag: '🇲🇲',
    callingCode: '+95',
  },
  {
    code: 'EG',
    name: 'Mısır',
    englishName: 'Egypt',
    flag: '🇪🇬',
    callingCode: '+20',
  },
  {
    code: 'NA',
    name: 'Namibya',
    englishName: 'Namibia',
    flag: '🇳🇦',
    callingCode: '+264',
  },
  {
    code: 'NR',
    name: 'Nauru',
    englishName: 'Nauru',
    flag: '🇳🇷',
    callingCode: '+674',
  },
  {
    code: 'NP',
    name: 'Nepal',
    englishName: 'Nepal',
    flag: '🇳🇵',
    callingCode: '+977',
  },
  {
    code: 'NE',
    name: 'Nijer',
    englishName: 'Niger',
    flag: '🇳🇪',
    callingCode: '+227',
  },
  {
    code: 'NG',
    name: 'Nijerya',
    englishName: 'Nigeria',
    flag: '🇳🇬',
    callingCode: '+234',
  },
  {
    code: 'NI',
    name: 'Nikaragua',
    englishName: 'Nicaragua',
    flag: '🇳🇮',
    callingCode: '+505',
  },
  {
    code: 'NU',
    name: 'Niue',
    englishName: 'Niue',
    flag: '🇳🇺',
    callingCode: '+683',
  },
  {
    code: 'NF',
    name: 'Norfolk Adası',
    englishName: 'Norfolk Island',
    flag: '🇳🇫',
    callingCode: '+672',
  },
  {
    code: 'NO',
    name: 'Norveç',
    englishName: 'Norway',
    flag: '🇳🇴',
    callingCode: '+47',
  },
  {
    code: 'CF',
    name: 'Orta Afrika Cumhuriyeti',
    englishName: 'Central African Republic',
    flag: '🇨🇫',
    callingCode: '+236',
  },
  {
    code: 'PK',
    name: 'Pakistan',
    englishName: 'Pakistan',
    flag: '🇵🇰',
    callingCode: '+92',
  },
  {
    code: 'PW',
    name: 'Palau',
    englishName: 'Palau',
    flag: '🇵🇼',
    callingCode: '+680',
  },
  {
    code: 'PA',
    name: 'Panama',
    englishName: 'Panama',
    flag: '🇵🇦',
    callingCode: '+507',
  },
  {
    code: 'PG',
    name: 'Papua Yeni Gine',
    englishName: 'Papua New Guinea',
    flag: '🇵🇬',
    callingCode: '+675',
  },
  {
    code: 'PY',
    name: 'Paraguay',
    englishName: 'Paraguay',
    flag: '🇵🇾',
    callingCode: '+595',
  },
  {
    code: 'PE',
    name: 'Peru',
    englishName: 'Peru',
    flag: '🇵🇪',
    callingCode: '+51',
  },
  {
    code: 'PL',
    name: 'Polonya',
    englishName: 'Poland',
    flag: '🇵🇱',
    callingCode: '+48',
  },
  {
    code: 'PT',
    name: 'Portekiz',
    englishName: 'Portugal',
    flag: '🇵🇹',
    callingCode: '+351',
  },
  {
    code: 'PR',
    name: 'Porto Riko',
    englishName: 'Puerto Rico',
    flag: '🇵🇷',
    callingCode: '+1',
  },
  {
    code: 'RO',
    name: 'Romanya',
    englishName: 'Romania',
    flag: '🇷🇴',
    callingCode: '+40',
  },
  {
    code: 'RW',
    name: 'Ruanda',
    englishName: 'Rwanda',
    flag: '🇷🇼',
    callingCode: '+250',
  },
  {
    code: 'RU',
    name: 'Rusya',
    englishName: 'Russia',
    flag: '🇷🇺',
    callingCode: '+7',
  },
  {
    code: 'RE',
    name: 'Réunion',
    englishName: 'Réunion',
    flag: '🇷🇪',
    callingCode: '+262',
  },
  {
    code: 'EH',
    name: 'Sahra Demokratik Arap Cumhuriyeti',
    englishName: 'Western Sahara',
    flag: '🇪🇭',
    callingCode: '+212',
  },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
    englishName: 'Saint Barthélemy',
    flag: '🇧🇱',
    callingCode: '+590',
  },
  {
    code: 'SH',
    name: 'Saint Helena',
    englishName: 'Saint Helena, Ascension and Tristan da Cunha',
    flag: '🇸🇭',
    callingCode: '+290',
  },
  {
    code: 'KN',
    name: 'Saint Kitts ve Nevis',
    englishName: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    callingCode: '+1',
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    englishName: 'Saint Lucia',
    flag: '🇱🇨',
    callingCode: '+1',
  },
  {
    code: 'MF',
    name: 'Saint Martin',
    englishName: 'Saint Martin',
    flag: '🇲🇫',
    callingCode: '+590',
  },
  {
    code: 'PM',
    name: 'Saint Pierre ve Miquelon',
    englishName: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    callingCode: '+508',
  },
  {
    code: 'VC',
    name: 'Saint Vincent ve Grenadinler',
    englishName: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    callingCode: '+1',
  },
  {
    code: 'SM',
    name: 'San Marino',
    englishName: 'San Marino',
    flag: '🇸🇲',
    callingCode: '+378',
  },
  {
    code: 'SN',
    name: 'Senegal',
    englishName: 'Senegal',
    flag: '🇸🇳',
    callingCode: '+221',
  },
  {
    code: 'SC',
    name: 'Seyşeller',
    englishName: 'Seychelles',
    flag: '🇸🇨',
    callingCode: '+248',
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    englishName: 'Sierra Leone',
    flag: '🇸🇱',
    callingCode: '+232',
  },
  {
    code: 'SG',
    name: 'Singapur',
    englishName: 'Singapore',
    flag: '🇸🇬',
    callingCode: '+65',
  },
  {
    code: 'SX',
    name: 'Sint Maarten',
    englishName: 'Sint Maarten',
    flag: '🇸🇽',
    callingCode: '+1',
  },
  {
    code: 'SK',
    name: 'Slovakya',
    englishName: 'Slovakia',
    flag: '🇸🇰',
    callingCode: '+421',
  },
  {
    code: 'SI',
    name: 'Slovenya',
    englishName: 'Slovenia',
    flag: '🇸🇮',
    callingCode: '+386',
  },
  {
    code: 'SB',
    name: 'Solomon Adaları',
    englishName: 'Solomon Islands',
    flag: '🇸🇧',
    callingCode: '+677',
  },
  {
    code: 'SO',
    name: 'Somali',
    englishName: 'Somalia',
    flag: '🇸🇴',
    callingCode: '+252',
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    englishName: 'Sri Lanka',
    flag: '🇱🇰',
    callingCode: '+94',
  },
  {
    code: 'SD',
    name: 'Sudan',
    englishName: 'Sudan',
    flag: '🇸🇩',
    callingCode: '+249',
  },
  {
    code: 'SR',
    name: 'Surinam',
    englishName: 'Suriname',
    flag: '🇸🇷',
    callingCode: '+597',
  },
  {
    code: 'SY',
    name: 'Suriye',
    englishName: 'Syria',
    flag: '🇸🇾',
    callingCode: '+963',
  },
  {
    code: 'SA',
    name: 'Suudi Arabistan',
    englishName: 'Saudi Arabia',
    flag: '🇸🇦',
    callingCode: '+966',
  },
  {
    code: 'SJ',
    name: 'Svalbard ve Jan Mayen',
    englishName: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
    callingCode: '+47',
  },
  {
    code: 'ST',
    name: 'São Tomé ve Príncipe',
    englishName: 'São Tomé and Príncipe',
    flag: '🇸🇹',
    callingCode: '+239',
  },
  {
    code: 'RS',
    name: 'Sırbistan',
    englishName: 'Serbia',
    flag: '🇷🇸',
    callingCode: '+381',
  },
  {
    code: 'TJ',
    name: 'Tacikistan',
    englishName: 'Tajikistan',
    flag: '🇹🇯',
    callingCode: '+992',
  },
  {
    code: 'TZ',
    name: 'Tanzanya',
    englishName: 'Tanzania',
    flag: '🇹🇿',
    callingCode: '+255',
  },
  {
    code: 'TH',
    name: 'Tayland',
    englishName: 'Thailand',
    flag: '🇹🇭',
    callingCode: '+66',
  },
  {
    code: 'TW',
    name: 'Tayvan',
    englishName: 'Taiwan',
    flag: '🇹🇼',
    callingCode: '+886',
  },
  {
    code: 'TG',
    name: 'Togo',
    englishName: 'Togo',
    flag: '🇹🇬',
    callingCode: '+228',
  },
  {
    code: 'TK',
    name: 'Tokelau',
    englishName: 'Tokelau',
    flag: '🇹🇰',
    callingCode: '+690',
  },
  {
    code: 'TO',
    name: 'Tonga',
    englishName: 'Tonga',
    flag: '🇹🇴',
    callingCode: '+676',
  },
  {
    code: 'TT',
    name: 'Trinidad ve Tobago',
    englishName: 'Trinidad and Tobago',
    flag: '🇹🇹',
    callingCode: '+1',
  },
  {
    code: 'TN',
    name: 'Tunus',
    englishName: 'Tunisia',
    flag: '🇹🇳',
    callingCode: '+216',
  },
  {
    code: 'TC',
    name: 'Turks ve Caicos Adaları',
    englishName: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    callingCode: '+1',
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    englishName: 'Tuvalu',
    flag: '🇹🇻',
    callingCode: '+688',
  },
  {
    code: 'TR',
    name: 'Türkiye',
    englishName: 'Türkiye',
    flag: '🇹🇷',
    callingCode: '+90',
  },
  {
    code: 'TM',
    name: 'Türkmenistan',
    englishName: 'Turkmenistan',
    flag: '🇹🇲',
    callingCode: '+993',
  },
  {
    code: 'UG',
    name: 'Uganda',
    englishName: 'Uganda',
    flag: '🇺🇬',
    callingCode: '+256',
  },
  {
    code: 'UA',
    name: 'Ukrayna',
    englishName: 'Ukraine',
    flag: '🇺🇦',
    callingCode: '+380',
  },
  {
    code: 'OM',
    name: 'Umman',
    englishName: 'Oman',
    flag: '🇴🇲',
    callingCode: '+968',
  },
  {
    code: 'UY',
    name: 'Uruguay',
    englishName: 'Uruguay',
    flag: '🇺🇾',
    callingCode: '+598',
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    englishName: 'Vanuatu',
    flag: '🇻🇺',
    callingCode: '+678',
  },
  {
    code: 'VA',
    name: 'Vatikan',
    englishName: 'Vatican City',
    flag: '🇻🇦',
    callingCode: '+39',
  },
  {
    code: 'VE',
    name: 'Venezuela',
    englishName: 'Venezuela',
    flag: '🇻🇪',
    callingCode: '+58',
  },
  {
    code: 'VN',
    name: 'Vietnam',
    englishName: 'Vietnam',
    flag: '🇻🇳',
    callingCode: '+84',
  },
  {
    code: 'VG',
    name: 'Virjin Adaları',
    englishName: 'British Virgin Islands',
    flag: '🇻🇬',
    callingCode: '+1',
  },
  {
    code: 'WF',
    name: 'Wallis ve Futuna Adaları Bölgesi',
    englishName: 'Wallis and Futuna',
    flag: '🇼🇫',
    callingCode: '+681',
  },
  {
    code: 'YE',
    name: 'Yemen',
    englishName: 'Yemen',
    flag: '🇾🇪',
    callingCode: '+967',
  },
  {
    code: 'NC',
    name: 'Yeni Kaledonya',
    englishName: 'New Caledonia',
    flag: '🇳🇨',
    callingCode: '+687',
  },
  {
    code: 'NZ',
    name: 'Yeni Zelanda',
    englishName: 'New Zealand',
    flag: '🇳🇿',
    callingCode: '+64',
  },
  {
    code: 'CV',
    name: 'Yeşil Burun',
    englishName: 'Cape Verde',
    flag: '🇨🇻',
    callingCode: '+238',
  },
  {
    code: 'GR',
    name: 'Yunanistan',
    englishName: 'Greece',
    flag: '🇬🇷',
    callingCode: '+30',
  },
  {
    code: 'ZM',
    name: 'Zambiya',
    englishName: 'Zambia',
    flag: '🇿🇲',
    callingCode: '+260',
  },
  {
    code: 'ZW',
    name: 'Zimbabve',
    englishName: 'Zimbabwe',
    flag: '🇿🇼',
    callingCode: '+263',
  },
  {
    code: 'AX',
    name: 'Åland',
    englishName: 'Åland Islands',
    flag: '🇦🇽',
    callingCode: '+358',
  },
  {
    code: 'TD',
    name: 'çad',
    englishName: 'Chad',
    flag: '🇹🇩',
    callingCode: '+235',
  },
  {
    code: 'CZ',
    name: 'çekya',
    englishName: 'Czechia',
    flag: '🇨🇿',
    callingCode: '+420',
  },
  {
    code: 'CN',
    name: 'çin',
    englishName: 'China',
    flag: '🇨🇳',
    callingCode: '+86',
  },
  {
    code: 'UZ',
    name: 'özbekistan',
    englishName: 'Uzbekistan',
    flag: '🇺🇿',
    callingCode: '+998',
  },
  {
    code: 'JO',
    name: 'ürdün',
    englishName: 'Jordan',
    flag: '🇯🇴',
    callingCode: '+962',
  },
  {
    code: 'IR',
    name: 'İran',
    englishName: 'Iran',
    flag: '🇮🇷',
    callingCode: '+98',
  },
  {
    code: 'IE',
    name: 'İrlanda',
    englishName: 'Ireland',
    flag: '🇮🇪',
    callingCode: '+353',
  },
  {
    code: 'ES',
    name: 'İspanya',
    englishName: 'Spain',
    flag: '🇪🇸',
    callingCode: '+34',
  },
  {
    code: 'IL',
    name: 'İsrail',
    englishName: 'Israel',
    flag: '🇮🇱',
    callingCode: '+972',
  },
  {
    code: 'SE',
    name: 'İsveç',
    englishName: 'Sweden',
    flag: '🇸🇪',
    callingCode: '+46',
  },
  {
    code: 'CH',
    name: 'İsviçre',
    englishName: 'Switzerland',
    flag: '🇨🇭',
    callingCode: '+41',
  },
  {
    code: 'IT',
    name: 'İtalya',
    englishName: 'Italy',
    flag: '🇮🇹',
    callingCode: '+39',
  },
  {
    code: 'IS',
    name: 'İzlanda',
    englishName: 'Iceland',
    flag: '🇮🇸',
    callingCode: '+354',
  },
  {
    code: 'CL',
    name: 'şili',
    englishName: 'Chile',
    flag: '🇨🇱',
    callingCode: '+56',
  },
];
